/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopractico3;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfondo = new javax.swing.JPanel();
        Jtitulo = new javax.swing.JLabel();
        jnumc = new javax.swing.JTextField();
        jconvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfondo.setBackground(new java.awt.Color(102, 102, 102));

        Jtitulo.setBackground(new java.awt.Color(153, 153, 0));
        Jtitulo.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        Jtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jtitulo.setText("Convertidor de Celsius a Fahrenheit");
        Jtitulo.setOpaque(true);

        jnumc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnumcActionPerformed(evt);
            }
        });

        jconvert.setBackground(new java.awt.Color(0, 102, 204));
        jconvert.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jconvert.setForeground(new java.awt.Color(255, 0, 0));
        jconvert.setText("Convertir");
        jconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfondoLayout = new javax.swing.GroupLayout(jfondo);
        jfondo.setLayout(jfondoLayout);
        jfondoLayout.setHorizontalGroup(
            jfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfondoLayout.createSequentialGroup()
                .addGroup(jfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfondoLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jnumc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfondoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jfondoLayout.setVerticalGroup(
            jfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Jtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jnumc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnumcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnumcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnumcActionPerformed

    private void jconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconvertActionPerformed
       
        try{
        double num = Double.parseDouble(jnumc.getText());
       double Fahrenheit = num * 9/5 + 32;
       
       JOptionPane.showMessageDialog(this, "Convertido: " + Fahrenheit);
        }catch(NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "¡Solo puede ingresar enteros o decimales!", "Datos incorrectos ingresados", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jconvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jtitulo;
    private javax.swing.JButton jconvert;
    private javax.swing.JPanel jfondo;
    private javax.swing.JTextField jnumc;
    // End of variables declaration//GEN-END:variables
}
